### ISSUE TITLE
JavaScript 

### ISSUE THREAD

**Issue by Rishabh-kr37** [Rishabh-kr37/css-projectKFC#1]
error in next button

**Comment by andreluisklr** [comment]
[css-projectKFC-main-edited.zip](https://github.com/Rishabh-kr37/css-projectKFC/files/7262904/css-projectKFC-main-edited.zip)
here is a way to make it work.

**Comment by Rishabh-kr37** [comment]
thanks man its working. am in learning period so its means a lot
